package common;

public enum NameType {
    EMPTY,
    DEFAULT,
    TEST_CASE,
    MALE_FORENAME,
    FEMALE_FORENAME,
    DOUBLE_BARRELLED_MALE_FORENAME,
    DOUBLE_BARRELLED_FEMALE_FORENAME,
    DOUBLE_MALE_FORENAME,
    DOUBLE_FEMALE_FORENAME,
    SURNAME,
    DUAL_SURNAME,
    SIMPLE_MALE_NAME,
    SIMPLE_FEMALE_NAME
}
