package common;

public enum OccupationType {
    ANY,
    MALE_OCCUPATION,
    FEMALE_OCCUPATION,
    GENDERLESS_OCCUPATION,
    MALE_JOB_TITLE,
    FEMALE_JOB_TITLE,
    GENDERLESS_JOB_TITLE,
    MALE_FANTASY_CLASS,
    FEMALE_FANTASY_CLASS,
    GENDERLESS_FANTASY_CLASS
}
